package com.jelly.farmhelperv3.config;

import org.lwjgl.glfw.GLFW;

/** LWJGL 2 scan codes stored by V2 are not GLFW key codes. */
public final class LegacyKeys {
    public static int toGlfw(int key) {
        if (key >= -100 && key <= -93) return key;
        return switch (key) {
            case 0 -> GLFW.GLFW_KEY_UNKNOWN;
            case 1 -> GLFW.GLFW_KEY_ESCAPE;
            case 2 -> GLFW.GLFW_KEY_1;
            case 3 -> GLFW.GLFW_KEY_2;
            case 4 -> GLFW.GLFW_KEY_3;
            case 5 -> GLFW.GLFW_KEY_4;
            case 6 -> GLFW.GLFW_KEY_5;
            case 7 -> GLFW.GLFW_KEY_6;
            case 8 -> GLFW.GLFW_KEY_7;
            case 9 -> GLFW.GLFW_KEY_8;
            case 10 -> GLFW.GLFW_KEY_9;
            case 11 -> GLFW.GLFW_KEY_0;
            case 12 -> GLFW.GLFW_KEY_MINUS;
            case 13 -> GLFW.GLFW_KEY_EQUAL;
            case 14 -> GLFW.GLFW_KEY_BACKSPACE;
            case 15 -> GLFW.GLFW_KEY_TAB;
            case 16 -> GLFW.GLFW_KEY_Q;
            case 17 -> GLFW.GLFW_KEY_W;
            case 18 -> GLFW.GLFW_KEY_E;
            case 19 -> GLFW.GLFW_KEY_R;
            case 20 -> GLFW.GLFW_KEY_T;
            case 21 -> GLFW.GLFW_KEY_Y;
            case 22 -> GLFW.GLFW_KEY_U;
            case 23 -> GLFW.GLFW_KEY_I;
            case 24 -> GLFW.GLFW_KEY_O;
            case 25 -> GLFW.GLFW_KEY_P;
            case 26 -> GLFW.GLFW_KEY_LEFT_BRACKET;
            case 27 -> GLFW.GLFW_KEY_RIGHT_BRACKET;
            case 28 -> GLFW.GLFW_KEY_ENTER;
            case 29 -> GLFW.GLFW_KEY_LEFT_CONTROL;
            case 30 -> GLFW.GLFW_KEY_A;
            case 31 -> GLFW.GLFW_KEY_S;
            case 32 -> GLFW.GLFW_KEY_D;
            case 33 -> GLFW.GLFW_KEY_F;
            case 34 -> GLFW.GLFW_KEY_G;
            case 35 -> GLFW.GLFW_KEY_H;
            case 36 -> GLFW.GLFW_KEY_J;
            case 37 -> GLFW.GLFW_KEY_K;
            case 38 -> GLFW.GLFW_KEY_L;
            case 39 -> GLFW.GLFW_KEY_SEMICOLON;
            case 40 -> GLFW.GLFW_KEY_APOSTROPHE;
            case 41 -> GLFW.GLFW_KEY_GRAVE_ACCENT;
            case 42 -> GLFW.GLFW_KEY_LEFT_SHIFT;
            case 43 -> GLFW.GLFW_KEY_BACKSLASH;
            case 44 -> GLFW.GLFW_KEY_Z;
            case 45 -> GLFW.GLFW_KEY_X;
            case 46 -> GLFW.GLFW_KEY_C;
            case 47 -> GLFW.GLFW_KEY_V;
            case 48 -> GLFW.GLFW_KEY_B;
            case 49 -> GLFW.GLFW_KEY_N;
            case 50 -> GLFW.GLFW_KEY_M;
            case 51 -> GLFW.GLFW_KEY_COMMA;
            case 52 -> GLFW.GLFW_KEY_PERIOD;
            case 53 -> GLFW.GLFW_KEY_SLASH;
            case 54 -> GLFW.GLFW_KEY_RIGHT_SHIFT;
            case 55 -> GLFW.GLFW_KEY_KP_MULTIPLY;
            case 56 -> GLFW.GLFW_KEY_LEFT_ALT;
            case 57 -> GLFW.GLFW_KEY_SPACE;
            case 58 -> GLFW.GLFW_KEY_CAPS_LOCK;
            case 59 -> GLFW.GLFW_KEY_F1;
            case 60 -> GLFW.GLFW_KEY_F2;
            case 61 -> GLFW.GLFW_KEY_F3;
            case 62 -> GLFW.GLFW_KEY_F4;
            case 63 -> GLFW.GLFW_KEY_F5;
            case 64 -> GLFW.GLFW_KEY_F6;
            case 65 -> GLFW.GLFW_KEY_F7;
            case 66 -> GLFW.GLFW_KEY_F8;
            case 67 -> GLFW.GLFW_KEY_F9;
            case 68 -> GLFW.GLFW_KEY_F10;
            case 69 -> GLFW.GLFW_KEY_NUM_LOCK;
            case 70 -> GLFW.GLFW_KEY_SCROLL_LOCK;
            case 71 -> GLFW.GLFW_KEY_KP_7;
            case 72 -> GLFW.GLFW_KEY_KP_8;
            case 73 -> GLFW.GLFW_KEY_KP_9;
            case 74 -> GLFW.GLFW_KEY_KP_SUBTRACT;
            case 75 -> GLFW.GLFW_KEY_KP_4;
            case 76 -> GLFW.GLFW_KEY_KP_5;
            case 77 -> GLFW.GLFW_KEY_KP_6;
            case 78 -> GLFW.GLFW_KEY_KP_ADD;
            case 79 -> GLFW.GLFW_KEY_KP_1;
            case 80 -> GLFW.GLFW_KEY_KP_2;
            case 81 -> GLFW.GLFW_KEY_KP_3;
            case 82 -> GLFW.GLFW_KEY_KP_0;
            case 83 -> GLFW.GLFW_KEY_KP_DECIMAL;
            case 87 -> GLFW.GLFW_KEY_F11;
            case 88 -> GLFW.GLFW_KEY_F12;
            case 100 -> GLFW.GLFW_KEY_F13;
            case 101 -> GLFW.GLFW_KEY_F14;
            case 102 -> GLFW.GLFW_KEY_F15;
            case 103 -> GLFW.GLFW_KEY_F16;
            case 104 -> GLFW.GLFW_KEY_F17;
            case 105 -> GLFW.GLFW_KEY_F18;
            case 113 -> GLFW.GLFW_KEY_F19;
            case 141 -> GLFW.GLFW_KEY_KP_EQUAL;
            case 156 -> GLFW.GLFW_KEY_KP_ENTER;
            case 157 -> GLFW.GLFW_KEY_RIGHT_CONTROL;
            case 181 -> GLFW.GLFW_KEY_KP_DIVIDE;
            case 183 -> GLFW.GLFW_KEY_PRINT_SCREEN;
            case 184 -> GLFW.GLFW_KEY_RIGHT_ALT;
            case 197 -> GLFW.GLFW_KEY_PAUSE;
            case 199 -> GLFW.GLFW_KEY_HOME;
            case 200 -> GLFW.GLFW_KEY_UP;
            case 201 -> GLFW.GLFW_KEY_PAGE_UP;
            case 203 -> GLFW.GLFW_KEY_LEFT;
            case 205 -> GLFW.GLFW_KEY_RIGHT;
            case 207 -> GLFW.GLFW_KEY_END;
            case 208 -> GLFW.GLFW_KEY_DOWN;
            case 209 -> GLFW.GLFW_KEY_PAGE_DOWN;
            case 210 -> GLFW.GLFW_KEY_INSERT;
            case 211 -> GLFW.GLFW_KEY_DELETE;
            case 219 -> GLFW.GLFW_KEY_LEFT_SUPER;
            case 220 -> GLFW.GLFW_KEY_RIGHT_SUPER;
            case 221 -> GLFW.GLFW_KEY_MENU;
            default -> GLFW.GLFW_KEY_UNKNOWN;
        };
    }
}
